site_name: AME Consulting Documentation
site_url: https://sitename.example

nav:
  - Home: index.md
  - AME Timesheets:
      - AWS Infrastructure: ame-timesheets/aws-infra.md
      - CI/CD Pipeline: ame-timesheets/ci-cd.md
      - Backend (Django): ame-timesheets/backend.md
      - Frontend (React): ame-timesheets/frontend.md
  - How to Use MkDocs & Contribute:
      - Getting Started: how-to/contributing.md
  - Onboarding:
      - Environment Setup: onboarding/setup.md
      - Access & Permissions: onboarding/access.md
      - Project Overview: onboarding/projects.md

theme:
  name: material
  font:
    text: Inter
    code: Fira Code
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - toc.integrate
    - content.code.annotate
    - content.code.copy
  palette:
    - scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

repo_url: https://github.com/AME-Consulting-Ltd/ame-docs
repo_name: AME Docs
edit_uri: edit/main/docs/

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ame-consulting-ltd
    - icon: material/web
      link: https://www.ame-consulting.ca/

copyright: Copyright © 2024 AME Consulting Ltd.

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.details

plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      fallback_to_build_date: true
  - section-index
  - minify
